# Generated by Django 2.2.9 on 2020-01-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phote',
            new_name='photo',
        ),
    ]
